fix(celery): fix task_queues config format - use Queue objects instead of dicts
The Celery task_queues was using dict format which caused:
AttributeError: 'dict' object has no attribute 'name'

Changed to use kombu.Queue objects properly.